### ISSUE TITLE
Read Only world loaded at startup is being saved.

### ISSUE THREAD

**Issue by TheDeafCreeper** [InfernalSuite/AdvancedSlimePaper#44]
**Describe the issue**
readOnly world loaded at startup is being saved.

worlds.yml:
```yaml
worlds:
    WSArena:
        source: mysql
        spawn: 0, 74, 30
        difficulty: normal
        allowMonsters: true
        allowAnimals: false
        dragonBattle: false
        pvp: true
        environment: NORMAL
        worldType: default
        defaultBiome: minecraft:plains
        loadOnStartup: true
        readOnly: true
```

**Spigot version**
git-SlimeWorldManager-55 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 1cafc9a)
(Also happens on Git: c9973e)

**Plugin version**
2.10.0

**How to reproduce**
Load world at startup while also marked readOnly

**Crash reports (if available)**
